//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;
namespace EcommerceWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    

    public partial class ProductL
    {
        public int Id { get; set; }
        public string P_Name { get; set; }
        public string Price { get; set; }
        public string Quantity { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
